language: node_js
node_js:
  - 14
python:
  - 3.8.3
cache:
  npm: true
install:
  npm install
notifications:
  email:
    recipients:
      - u14272289@tuks.co.za
    on_success: never # default: change
    on_failure: always # default: always