dist: bionic
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
language: node_js
node_js:
  - 14
cache:
  npm: true
install:
  npm install
notifications:
  email:
    recipients:
      - u14272289@tuks.co.za
    on_success: never # default: change
    on_failure: always # default: always