language: node_js
node_js:
  - 14
cache:
  npm: true
install:
  npm install
notifications:
  email:
    recipients:
      - u15015069@tuks.co.za
      - u18028510@tuks.co.za
      - u14272289@tuks.co.za
      - u14126461@tuks.co.za
      - u18010408@tuks.co.za
    on_success: never # default: change
    on_failure: always # default: always