os: linux
dist: bionic
before_install:
  - pyenv global 3.8
language: node_js
node_js:
  - 14
cache:
  npm: true
install: bash build.sh
notifications:
  email:
    recipients:
      - u14272289@tuks.co.za
    on_success: never # default: change
    on_failure: always # default: always
