dist: bionic
env: PYTHON=3.8.2
language: node_js
node_js:
  - 14
cache:
  npm: true
install:
  npm install
notifications:
  email:
    recipients:
      - u14272289@tuks.co.za
    on_success: never # default: change
    on_failure: always # default: always