on:
  push:
    branches: master
  release:
    types: created

name: Deploy to Amazon EC2

jobs:
  build:

   name: Build
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Install Dependencies
       run: npm install
     - name: Run Tests
       run: npm test
     - name: Build and tag the image
       run: |
        docker build \
          -t $CONTAINER_IMAGE 

   
#   deploy:
#     needs: test
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy To EC2
#         uses: actions/upload-artifact@v2


    
