on:
  push:
    branches: master
  release:
    types: created

name: Deploy to Amazon EC2

jobs:
  build:
   name: Build
   runs-on: ubuntu-latest
   steps:
     - name: Install Dependencies
       run: npm install
   
  test:
   name: test
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Run Tests
       run: npm test
   
#   deploy:
#     needs: test
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy To EC2
#         uses: actions/upload-artifact@v2


    
